/**
 * ONE contract suite, TWO adapters — driven by REAL backend JSON.
 *
 * Every assertion in `runGatewayContract` is executed unchanged against the
 * deterministic `mock` adapter and against the `http` adapter driven by a stub
 * `fetch`. A surface must not be able to tell them apart, so anything the mock
 * is allowed to do the HTTP adapter has to do too, and vice versa.
 *
 * The HTTP payloads are NOT written by hand. They come from
 * `fixtures/real-mission-payloads.json`, which is generated by
 * `fixtures/generate-real-mission-payloads.py` importing the backend's own
 * pydantic response models and its reviewed catalog. That matters: the previous
 * version of this suite passed against a hand-written fixture that agreed with a
 * hand-written DTO, while the real API used different field names entirely —
 * `offer_id` vs `mission_id`, `slot` 1..3 vs `slot_index` 0..2, `detail.code`
 * vs `code`. Green tests, broken product. Feeding the mappers the real shape is
 * the only thing that catches that class of bug.
 */

import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { register } from 'node:module';

register('./mission-alias-hooks.mjs', import.meta.url);

/** Generated from the backend contracts. See the header above. */
const PAYLOADS = JSON.parse(
  readFileSync(new URL('./fixtures/real-mission-payloads.json', import.meta.url), 'utf8')
);

const { createMockGateway } = await import(
  '../src/features/missions/gateway/mock-mission-gateway-adapter.ts'
);
const { createHttpMissionGateway } = await import(
  '../src/features/missions/gateway/http-mission-gateway.ts'
);
const { MissionGatewayError } = await import(
  '../src/features/missions/gateway/mission-gateway.ts'
);
const {
  toMissionOffer,
  toActiveMission,
  toHomeMissions,
  toSelectionPayload,
  toProfileHub,
  idempotencyKeyFor,
} = await import('../src/features/missions/gateway/mission-api-mappers.ts');
const { isDraftComplete } = await import(
  '../src/features/missions/renderers/draft-validation.ts'
);

// ---------------------------------------------------------------------------
// Shared card context (the product's event endpoints own this, not missions)
// ---------------------------------------------------------------------------

const fighter = (name, corner) => ({ fighter_name: name, corner });

const CARD = {
  eventId: 999,
  eventName: 'UFC TEST CARD: Contract vs Adapter',
  eventImageUrl: null,
  bouts: [
    {
      id: 101,
      weightClass: 'Lightweight',
      section: 'main',
      isMainEvent: true,
      roundsScheduled: 5,
      red: fighter('Red One', 'red'),
      blue: fighter('Blue One', 'blue'),
    },
    {
      id: 102,
      weightClass: 'Welterweight',
      section: 'main',
      isCoMain: true,
      roundsScheduled: 3,
      red: fighter('Red Two', 'red'),
      blue: fighter('Blue Two', 'blue'),
    },
    {
      id: 103,
      weightClass: 'Flyweight',
      section: 'prelim',
      roundsScheduled: 3,
      red: fighter('Red Three', 'red'),
      blue: fighter('Blue Three', 'blue'),
    },
  ],
};

/** Used where a scenario has no open slot but selection must still be refused. */
const THROWAWAY_OFFER = {
  offerId: 'offer_deadbeefdeadbeef',
  missionId: 'CARD-V2-E-999',
  name: 'Throwaway',
  description: '',
  difficulty: 'EASY',
  xp: 1,
  progressTemplate: '',
  interaction: 'AUTO',
};

// ---------------------------------------------------------------------------
// Wire access helpers over the generated payloads
// ---------------------------------------------------------------------------

/** Every real offer across every slot of the open card. */
const REAL_OFFERS = PAYLOADS.home.open.slots.flatMap((slot) => slot.options);

const offerByMission = (missionId) => {
  const found = REAL_OFFERS.find((option) => option.mission_id === missionId);
  assert.ok(found, `fixture is missing catalog row ${missionId}`);
  return found;
};

const json = (body, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });

/** Records every request so URL/method/body can be asserted. */
function stubFetch(scenario) {
  const calls = [];
  // The real endpoint stamps `acknowledged_at` and stops listing the
  // celebration. The stub has to honour that too: a stub that always replays
  // the same profile makes the acknowledgement test pass without proving
  // anything.
  const acknowledged = new Set();
  const impl = async (url, init = {}) => {
    calls.push({
      url: String(url),
      method: init.method ?? 'GET',
      body: init.body,
      headers: init.headers,
    });
    const path = String(url);

    if (path.includes('/missions/home')) return json(PAYLOADS.home[scenario]);
    if (path.includes('/ack')) {
      const id = path.split('/celebrations/')[1]?.split('/')[0];
      if (id) acknowledged.add(decodeURIComponent(id));
      return new Response(null, { status: 204 });
    }
    if (path.includes('/missions/profile')) {
      return json({
        ...PAYLOADS.profile,
        celebrations: (PAYLOADS.profile.celebrations ?? []).filter(
          (celebration) => !acknowledged.has(celebration.id)
        ),
      });
    }

    if (path.includes('/missions/select')) {
      if (scenario === 'locked' || scenario === 'settled') {
        return json(PAYLOADS.errors.slot_locked_409, 409);
      }
      // The real endpoint answers 201, not 200.
      return json(PAYLOADS.select_201, 201);
    }
    return json(PAYLOADS.errors.card_not_found_404, 404);
  };
  return { impl, calls };
}

// ---------------------------------------------------------------------------
// Adapters under test
// ---------------------------------------------------------------------------

const MOCK_SCENARIO_IDS = {
  open: 'home-open',
  locked: 'home-locked',
  settled: 'home-settled',
  'no-offers': 'home-no-offers',
  'month-closed': 'home-month-closed',
};

const ADAPTERS = [
  {
    name: 'mock',
    create: (scenario) => createMockGateway({ scenarioId: MOCK_SCENARIO_IDS[scenario] }),
  },
  {
    name: 'http',
    create: (scenario) =>
      createHttpMissionGateway({
        baseUrl: '/api',
        fetchImpl: stubFetch(scenario).impl,
        getToken: () => 'test-token',
        now: () => new Date('2026-08-01T12:00:00Z'),
      }),
  },
];

// ---------------------------------------------------------------------------
// Invariants
// ---------------------------------------------------------------------------

const SLOT_STATES = new Set(['no-offers', 'open', 'locked', 'active', 'settled']);
const LOCK_REASONS = new Set(['picks-closed', 'admin-closed', 'results-started']);
const MONTHLY_STATES = new Set([
  'not-configured',
  'month-closed',
  'active',
  'near-completion',
  'completed',
]);
const INTERACTIONS = new Set([
  'AUTO',
  'TARGET_FIGHTER',
  'TARGET_FIGHT',
  'COMBO_BUILDER',
  'CARD_PROP',
]);
const PICK_EFFECTS = new Set(['NONE', 'UPSERT_ONE', 'UPSERT_MANY']);

/**
 * The complete set of keys a surface is allowed to see on an active mission.
 * Every one of them is already resolved. If a raw domain input (a target, a
 * threshold, a rule) ever leaks into the view model, React becomes able to
 * recompute progress and this fails.
 */
const MISSION_KEYS = new Set([
  'missionId', 'name', 'interaction', 'difficulty', 'xp',
  'selectionSummary', 'selection', 'targetBoutId', 'targetCorner', 'targetFighter',
  'progressText', 'progress', 'progressCompare', 'progressPct',
  'status', 'voidReason', 'earnedXp',
]);

const OFFER_KEYS = new Set([
  'offerId', 'missionId', 'name', 'description', 'difficulty', 'xp',
  'progressTemplate', 'selectionPrompt', 'pickEffect', 'interaction',
  'requiresMethod', 'requiresRound', 'allowedMethods', 'allowedRounds',
  'winnerBinding', 'titleBoutsOnly',
  'outcome', 'requiredRound',
  'legCount', 'legRule', 'legLabels', 'legs', 'legTarget',
  'distinctMethods', 'distinctBouts',
  'propKind', 'choices', 'displayedTarget', 'maxCount', 'countUnit',
]);

function assertResolvedMission(mission, label) {
  for (const key of Object.keys(mission)) {
    assert.ok(MISSION_KEYS.has(key), `${label}: unexpected view-model key "${key}"`);
  }
  assert.equal(typeof mission.progressText, 'string', `${label}: progressText must arrive resolved`);
  assert.equal(typeof mission.progressPct, 'number', `${label}: progressPct must arrive resolved`);
  assert.ok(
    mission.progressPct >= 0 && mission.progressPct <= 100,
    `${label}: progressPct ${mission.progressPct} out of range`
  );
  assert.equal(typeof mission.xp, 'number', `${label}: xp must arrive resolved`);
  assert.ok(INTERACTIONS.has(mission.interaction), `${label}: bad interaction`);
  if (mission.status === 'VOID') {
    assert.equal(typeof mission.voidReason, 'string', `${label}: VOID needs a resolved reason`);
  }
}

function assertRenderableOffer(offer, label) {
  for (const key of Object.keys(offer)) {
    assert.ok(OFFER_KEYS.has(key), `${label}: unexpected offer key "${key}"`);
  }
  assert.ok(INTERACTIONS.has(offer.interaction), `${label}: bad interaction`);
  assert.equal(typeof offer.offerId, 'string');
  assert.ok(offer.offerId.length > 0, `${label}: an offer without an id cannot be selected`);
  assert.equal(typeof offer.missionId, 'string');
  assert.equal(typeof offer.xp, 'number');
  if (offer.pickEffect !== undefined) {
    assert.ok(PICK_EFFECTS.has(offer.pickEffect), `${label}: bad pick effect`);
  }

  // The discriminant has to carry its family's data with it.
  switch (offer.interaction) {
    case 'COMBO_BUILDER':
      assert.ok([2, 3].includes(offer.legCount), `${label}: combo needs legCount 2|3`);
      assert.equal(typeof offer.legRule, 'string', `${label}: combo needs a leg rule`);
      break;
    case 'CARD_PROP':
      assert.ok(
        ['accept', 'choice', 'exact-count'].includes(offer.propKind),
        `${label}: prop needs a propKind`
      );
      break;
    case 'TARGET_FIGHTER':
      if (offer.requiresRound) {
        const methods = offer.allowedMethods ?? ['KO/TKO', 'Submission', 'Decision'];
        assert.ok(
          !methods.includes('Decision'),
          `${label}: a round-exact mission must never offer Decision`
        );
      }
      break;
    default:
      break;
  }
}

// ---------------------------------------------------------------------------
// The shared contract
// ---------------------------------------------------------------------------

function runGatewayContract(adapter) {
  const scoped = (title) => `[${adapter.name}] ${title}`;
  const home = (scenario) => adapter.create(scenario).getHome({ eventId: 999, card: CARD });

  test(scoped('getHome returns a presentation-ready Home view model'), async () => {
    const vm = await home('open');

    assert.deepEqual(vm.event, CARD, 'the card comes from the caller, not the mission payload');
    assert.equal(typeof vm.lockLabel, 'string');
    assert.ok(vm.lockLabel.length > 0, 'lock language must always be present');
    assert.ok(MONTHLY_STATES.has(vm.monthly.state));
    assert.equal(vm.slots.length, 3);
    assert.deepEqual(vm.slots.map((s) => s.slot), [1, 2, 3], 'slots are numbered 1..3 for the UI');
    for (const slot of vm.slots) {
      assert.ok(SLOT_STATES.has(slot.state), `unknown slot state ${slot.state}`);
    }
  });

  test(scoped('open slots offer renderable, discriminated offers'), async () => {
    const vm = await home('open');
    const open = vm.slots.filter((s) => s.state === 'open');
    assert.ok(open.length > 0, 'the open scenario must expose at least one open slot');

    for (const slot of open) {
      assert.ok(slot.offers.length > 0, `slot ${slot.slot} is open but offers nothing`);
      for (const offer of slot.offers) {
        assertRenderableOffer(offer, `slot ${slot.slot} offer ${offer.offerId}`);
      }
    }
  });

  test(scoped('a locked card offers nothing and states one lock reason'), async () => {
    const vm = await home('locked');

    assert.ok(vm.lockLabel.includes('LOCKED'), `lock label "${vm.lockLabel}" must read as locked`);
    for (const slot of vm.slots) {
      assert.notEqual(slot.state, 'open', `slot ${slot.slot} still offers picks while locked`);
      if (slot.state === 'locked') {
        assert.ok(LOCK_REASONS.has(slot.reason), `unknown lock reason ${slot.reason}`);
      }
    }
  });

  test(scoped('settled slots carry resolved progress, VOID reasons and XP'), async () => {
    const vm = await home('settled');
    const settled = vm.slots.filter((s) => s.state === 'settled' || s.state === 'active');
    assert.ok(settled.length > 0, 'the settled scenario must expose settled missions');

    for (const slot of settled) {
      assertResolvedMission(slot.mission, `slot ${slot.slot}`);
    }

    const statuses = settled.map((s) => s.mission.status);
    assert.ok(statuses.includes('COMPLETED'), 'a completed mission must render');
    assert.ok(statuses.includes('VOID'), 'a VOID mission must render');
  });

  test(scoped('an empty card renders no-offers and an unconfigured month'), async () => {
    const vm = await home('no-offers');

    assert.ok(
      vm.slots.some((s) => s.state === 'no-offers'),
      'an empty card must produce at least one no-offers slot'
    );
    assert.equal(vm.monthly.state, 'not-configured');
    assert.equal(typeof vm.monthly.monthLabel, 'string');
    assert.ok(vm.monthly.monthLabel.length > 0, 'the unconfigured month still needs a label');
  });

  test(scoped('a closed month renders its final text, not a live meter'), async () => {
    const vm = await home('month-closed');

    assert.equal(vm.monthly.state, 'month-closed');
    assert.equal(typeof vm.monthly.name, 'string');
    assert.equal(typeof vm.monthly.finalText, 'string');
    assert.ok(vm.monthly.finalText.length > 0);
  });

  test(scoped('select accepts an open offer and returns the resulting mission'), async () => {
    const gateway = adapter.create('open');
    const vm = await gateway.getHome({ eventId: 999, card: CARD });
    const slot = vm.slots.find((s) => s.state === 'open');
    const offer = slot.offers[0];

    const mission = await gateway.select({
      eventId: 999,
      slot: slot.slot,
      offer,
      selection: { kind: 'AUTO' },
    });

    assertResolvedMission(mission, 'selected mission');
    assert.ok(
      ['ACTIVE', 'COMPLETED', 'FAILED', 'VOID', 'ONE_TO_GO'].includes(mission.status),
      `unexpected status ${mission.status}`
    );
  });

  test(scoped('select is refused when the slot is locked'), async () => {
    const gateway = adapter.create('locked');
    await assert.rejects(
      () =>
        gateway.select({
          eventId: 999,
          slot: 1,
          offer: THROWAWAY_OFFER,
          selection: { kind: 'AUTO' },
        }),
      (error) => {
        assert.ok(error instanceof Error, 'a refusal must be an Error');
        if (error instanceof MissionGatewayError) {
          assert.ok(
            ['SLOT_LOCKED', 'CARD_LOCKED', 'ALREADY_SELECTED', 'IDEMPOTENCY_CONFLICT'].includes(
              error.code
            ),
            `unexpected conflict code ${error.code}`
          );
        }
        return true;
      }
    );
  });

  test(scoped('getProfile returns resolved level and streak numbers'), async () => {
    const profile = await adapter.create('open').getProfile();

    assert.equal(typeof profile.level.level, 'number');
    assert.equal(typeof profile.level.lifetimeXp, 'number');
    assert.equal(typeof profile.level.levelProgressPct, 'number');
    assert.equal(typeof profile.streak.current, 'number');
    assert.equal(typeof profile.streak.best, 'number');
    assert.ok(Array.isArray(profile.activeMissions));
    assert.ok(Array.isArray(profile.history));
    assert.ok(Array.isArray(profile.pendingCelebrations));

    for (const mission of profile.activeMissions) {
      assertResolvedMission(mission, 'profile active mission');
    }
    for (const celebration of profile.pendingCelebrations) {
      assert.equal(typeof celebration.id, 'string', 'ack needs a stable identity, not a position');
    }
  });

  test(scoped('acknowledging a celebration resolves and is idempotent'), async () => {
    const gateway = adapter.create('open');
    const before = await gateway.getProfile();

    const target = before.pendingCelebrations[0];
    const id = target?.id ?? 'celebration-that-does-not-exist';

    await gateway.acknowledgeCelebration(id);
    await gateway.acknowledgeCelebration(id);

    const after = await gateway.getProfile();
    if (target) {
      assert.ok(
        !after.pendingCelebrations.some((c) => c.id === id),
        'an acknowledged celebration must not come back'
      );
    }
  });

  test(scoped('getHome is deterministic for the same inputs'), async () => {
    const gateway = adapter.create('open');
    const first = await gateway.getHome({ eventId: 999, card: CARD });
    const second = await gateway.getHome({ eventId: 999, card: CARD });
    assert.deepEqual(second, first);
  });
}

for (const adapter of ADAPTERS) {
  runGatewayContract(adapter);
}

// ---------------------------------------------------------------------------
// The fixture itself must stay real
// ---------------------------------------------------------------------------

test('[wire] the fixture is generated from the backend, not hand-written', () => {
  assert.equal(
    PAYLOADS._generated_by,
    'tests/fixtures/generate-real-mission-payloads.py',
    'the payloads must come from the generator that imports the backend contracts'
  );
  assert.match(PAYLOADS.catalog_version, /^\d{4}\.\d{2}\.\d{2}$/);

  // Field names the mappers depend on, asserted against the real payload.
  const home = PAYLOADS.home.open;
  assert.deepEqual(
    home.slots.map((s) => s.slot),
    [1, 2, 3],
    'MissionSlotView.slot is one-based on the wire'
  );
  for (const slot of home.slots) {
    assert.equal(slot.slot_index, undefined, 'there is no slot_index on this API');
    for (const option of slot.options) {
      assert.match(option.offer_id, /^offer_[a-f0-9]{8,64}$/, 'offers carry their own id');
      assert.notEqual(option.offer_id, option.mission_id);
    }
  }
  assert.equal(typeof home.monthly.month_key, 'string');
  assert.equal(home.monthly.month_label, undefined, 'the wire sends a key, not a label');
});

// ---------------------------------------------------------------------------
// HTTP-only: wire mapping is where recomputation would be tempting
// ---------------------------------------------------------------------------

test('[http] the adapter never recomputes progress from the text', () => {
  // Deliberately inconsistent: the sentence says 1 of 4, the backend says 87%.
  // The backend wins, because it is the authority.
  const mission = toActiveMission({
    ...PAYLOADS.select_201,
    progress_text: '1 / 4 winners',
    progress_percent: 87,
  });

  assert.equal(mission.progressPct, 87, 'the percent must be copied, never derived');
  assert.equal(mission.progressText, '1 / 4 winners');
  assert.equal(mission.progress, undefined, 'no split progress is invented from the sentence');
  assert.equal(mission.progressCompare, undefined);
});

test('[http] a selection summary is never split into parts', () => {
  const mission = toActiveMission({
    ...PAYLOADS.select_201,
    selection_summary: 'KO Rakic · SUB Klein · DEC Elliott',
  });

  assert.equal(mission.selectionSummary, 'KO Rakic · SUB Klein · DEC Elliott');
  assert.equal(mission.selection, undefined, 'splitting a combo sentence produces garbage');
});

test('[http] pick_effect is carried independently of interaction', () => {
  const auto = offerByMission('CARD-V2-E-004');
  for (const effect of ['NONE', 'UPSERT_ONE', 'UPSERT_MANY']) {
    const offer = toMissionOffer({ ...auto, pick_effect: effect });
    assert.equal(offer.interaction, 'AUTO');
    assert.equal(offer.pickEffect, effect, 'the same interaction must accept every pick effect');
  }
});

test('[http] an offer is addressed by offer_id, never by mission_id', () => {
  const wire = offerByMission('CARD-V2-E-001');
  const offer = toMissionOffer(wire);

  assert.equal(offer.offerId, wire.offer_id);
  assert.equal(offer.missionId, wire.mission_id);
  assert.notEqual(
    offer.offerId,
    offer.missionId,
    'using the mission id as the offer id is what made every select target the wrong option'
  );
});

test('[http] every real interaction maps into a renderable offer', () => {
  const mapped = REAL_OFFERS.map(toMissionOffer);
  const families = new Set(mapped.map((o) => o.interaction));
  for (const family of INTERACTIONS) {
    assert.ok(families.has(family), `wire mapping lost family ${family}`);
  }
  for (const offer of mapped) {
    assertRenderableOffer(offer, `offer ${offer.missionId}`);
  }
});

// ---------------------------------------------------------------------------
// selection_spec: derived from the real domain snapshot
// ---------------------------------------------------------------------------

test('[spec] TARGET_FIGHTER derives method/round requirements from bound_pick_fields', () => {
  const plain = toMissionOffer(offerByMission('CARD-V2-E-001'));
  assert.equal(plain.requiresMethod, false, 'WINNER-only missions ask for no method');
  assert.equal(plain.requiresRound, false);
  assert.equal(plain.allowedMethods, undefined, 'an empty allowed_methods means unrestricted');

  const exact = toMissionOffer(offerByMission('CARD-V2-H-003'));
  assert.equal(exact.requiresMethod, true);
  assert.equal(exact.requiresRound, true);
  // The wire spells methods KO_TKO/SUBMISSION; the UI shows KO/TKO and
  // Submission, and the order is canonical despite the frozenset arriving
  // unordered.
  assert.deepEqual(exact.allowedMethods, ['KO/TKO', 'Submission']);
  assert.deepEqual(exact.allowedRounds, [1, 2, 3, 4, 5]);
});

test('[spec] bound_pick_fields is read by membership, never by position', () => {
  const wire = offerByMission('CARD-V2-H-003');
  // pydantic frozensets serialize in arbitrary order — shuffling must not
  // change a single derived value.
  const shuffled = {
    ...wire,
    selection_spec: {
      ...wire.selection_spec,
      bound_pick_fields: [...wire.selection_spec.bound_pick_fields].reverse(),
      allowed_methods: [...wire.selection_spec.allowed_methods].reverse(),
    },
  };
  assert.deepEqual(toMissionOffer(shuffled), toMissionOffer(wire));
});

test('[spec] TARGET_FIGHT carries an outcome instead of a null spec', () => {
  const wire = offerByMission('CARD-V2-M-001');
  assert.notEqual(wire.selection_spec, null, 'the backend does send a spec here');
  const offer = toMissionOffer(wire);
  assert.equal(offer.outcome, 'FINISH');
  assert.equal(offer.requiredRound, undefined);
});

test('[spec] COMBO_BUILDER carries the leg keys the select command requires', () => {
  const fixed = toMissionOffer(offerByMission('CARD-V2-H-007'));
  assert.equal(fixed.legCount, 3);
  assert.equal(fixed.legTarget, 'FIGHTER');
  assert.deepEqual(
    fixed.legs.map((l) => l.key),
    ['ko_leg', 'submission_leg', 'decision_leg'],
    'a leg without its key cannot be submitted'
  );
  assert.deepEqual(
    fixed.legs.map((l) => l.method),
    ['KO/TKO', 'Submission', 'Decision'],
    'these methods are fixed by the catalog, not chosen by the user'
  );
  for (const leg of fixed.legs) {
    assert.equal(leg.allowedMethods, undefined, 'a fixed-method leg offers no choice');
  }

  const selectable = toMissionOffer(offerByMission('CARD-V2-M-013'));
  assert.equal(selectable.distinctMethods, true);
  for (const leg of selectable.legs) {
    assert.equal(leg.method, undefined, 'nothing is fixed here');
    assert.deepEqual(leg.allowedMethods, ['KO/TKO', 'Submission', 'Decision']);
  }

  const fights = toMissionOffer(offerByMission('CARD-V2-M-012'));
  assert.equal(fights.legTarget, 'FIGHT');
  for (const leg of fights.legs) {
    assert.equal(leg.fightOutcome, 'FINISH');
    assert.equal(leg.method, undefined);
  }
});

test('[spec] CARD_PROP maps all three inputs and invents no displayed target', () => {
  const accept = toMissionOffer(offerByMission('CARD-V2-E-012'));
  assert.equal(accept.propKind, 'accept');
  assert.equal(accept.choices, undefined);

  const choice = toMissionOffer(offerByMission('CARD-V3-E-008'));
  assert.equal(choice.propKind, 'choice');
  assert.deepEqual(choice.choices, ['FINISHES', 'DECISIONS']);

  const count = toMissionOffer(offerByMission('CARD-V2-H-019'));
  assert.equal(count.propKind, 'exact-count');
  // GAP 5: `target_source`/`frozen_ratio` are raw domain inputs. Resolving a
  // line from them in the client is exactly the recomputation this boundary
  // exists to prevent.
  assert.equal(count.displayedTarget, undefined);
});

// ---------------------------------------------------------------------------
// All five families open a picker and produce a payload the backend accepts
// ---------------------------------------------------------------------------

/**
 * `domain/selections.py` models are `extra="forbid"`, so an unexpected key is a
 * 422 before any handler runs. This is that rule, written down.
 */
const ALLOWED_PAYLOAD_KEYS = {
  AUTO: new Set(['kind']),
  TARGET_FIGHTER: new Set(['kind', 'bout_id', 'corner', 'method', 'round']),
  TARGET_FIGHT: new Set(['kind', 'bout_id']),
  COMBO_BUILDER: new Set(['kind', 'legs']),
  CARD_PROP: new Set(['kind', 'choice', 'exact_count']),
};
const ALLOWED_LEG_KEYS = new Set(['key', 'bout_id', 'corner', 'method']);
const WIRE_METHODS = new Set(['KO_TKO', 'SUBMISSION', 'DECISION']);

function assertWirePayload(payload, kind, label) {
  if (payload === null) return; // AUTO sends null; the router fills in the kind
  for (const key of Object.keys(payload)) {
    assert.ok(ALLOWED_PAYLOAD_KEYS[kind].has(key), `${label}: extra="forbid" rejects "${key}"`);
  }
  if (payload.method !== undefined) {
    assert.ok(WIRE_METHODS.has(payload.method), `${label}: "${payload.method}" is not a WinMethod`);
  }
  for (const leg of payload.legs ?? []) {
    for (const key of Object.keys(leg)) {
      assert.ok(ALLOWED_LEG_KEYS.has(key), `${label}: leg rejects "${key}"`);
    }
    assert.equal(typeof leg.key, 'string', `${label}: every leg needs its definition key`);
    assert.ok(leg.key.length > 0, `${label}: an empty leg key is rejected`);
    assert.equal(typeof leg.bout_id, 'number');
    if (leg.method !== undefined) {
      assert.ok(WIRE_METHODS.has(leg.method), `${label}: leg method "${leg.method}" is not a WinMethod`);
    }
  }
}

/** One representative complete draft per real catalog row. */
const PICKER_CASES = [
  {
    missionId: 'CARD-V2-E-004',
    kind: 'AUTO',
    draft: { kind: 'AUTO' },
    expect: null,
  },
  {
    missionId: 'CARD-V2-E-001',
    kind: 'TARGET_FIGHTER',
    draft: { kind: 'TARGET_FIGHTER', boutId: 101, corner: 'red' },
    expect: { kind: 'TARGET_FIGHTER', bout_id: 101, corner: 'red' },
  },
  {
    missionId: 'CARD-V2-H-003',
    kind: 'TARGET_FIGHTER',
    draft: {
      kind: 'TARGET_FIGHTER',
      boutId: 101,
      corner: 'blue',
      method: 'KO/TKO',
      round: 2,
    },
    expect: {
      kind: 'TARGET_FIGHTER',
      bout_id: 101,
      corner: 'blue',
      method: 'KO_TKO',
      round: 2,
    },
  },
  {
    missionId: 'CARD-V2-M-001',
    kind: 'TARGET_FIGHT',
    draft: { kind: 'TARGET_FIGHT', boutId: 102 },
    expect: { kind: 'TARGET_FIGHT', bout_id: 102 },
  },
  {
    missionId: 'CARD-V2-H-007',
    kind: 'COMBO_BUILDER',
    draft: {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'ko_leg', boutId: 101, corner: 'red' },
        { key: 'submission_leg', boutId: 102, corner: 'blue' },
        { key: 'decision_leg', boutId: 103, corner: 'red' },
      ],
    },
    expect: {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'ko_leg', bout_id: 101, corner: 'red' },
        { key: 'submission_leg', bout_id: 102, corner: 'blue' },
        { key: 'decision_leg', bout_id: 103, corner: 'red' },
      ],
    },
  },
  {
    missionId: 'CARD-V2-M-013',
    kind: 'COMBO_BUILDER',
    draft: {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'method_one', boutId: 101, corner: 'red', method: 'KO/TKO' },
        { key: 'method_two', boutId: 102, corner: 'blue', method: 'Submission' },
      ],
    },
    expect: {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'method_one', bout_id: 101, corner: 'red', method: 'KO_TKO' },
        { key: 'method_two', bout_id: 102, corner: 'blue', method: 'SUBMISSION' },
      ],
    },
  },
  {
    missionId: 'CARD-V2-M-012',
    kind: 'COMBO_BUILDER',
    draft: {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'finish_one', boutId: 101 },
        { key: 'finish_two', boutId: 102 },
      ],
    },
    // A FIGHT leg carries neither corner nor method.
    expect: {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'finish_one', bout_id: 101 },
        { key: 'finish_two', bout_id: 102 },
      ],
    },
  },
  {
    missionId: 'CARD-V2-E-012',
    kind: 'CARD_PROP',
    draft: { kind: 'CARD_PROP' },
    expect: { kind: 'CARD_PROP' },
  },
  {
    missionId: 'CARD-V3-E-008',
    kind: 'CARD_PROP',
    draft: { kind: 'CARD_PROP', choice: 'FINISHES' },
    expect: { kind: 'CARD_PROP', choice: 'FINISHES' },
  },
  {
    missionId: 'CARD-V2-H-019',
    kind: 'CARD_PROP',
    draft: { kind: 'CARD_PROP', exactCount: 4 },
    expect: { kind: 'CARD_PROP', exact_count: 4 },
  },
];

test('[picker] every real selection_spec opens a picker and completes a draft', () => {
  const covered = new Set();

  for (const testCase of PICKER_CASES) {
    const offer = toMissionOffer(offerByMission(testCase.missionId));
    const label = `${testCase.missionId} (${offer.interaction})`;
    covered.add(offer.interaction);

    assert.equal(offer.interaction, testCase.kind, `${label}: wrong family`);
    // Whatever the picker needs to render is on the offer, not left on a raw
    // spec the component would have to interpret.
    assert.ok(
      isDraftComplete(offer, testCase.draft),
      `${label}: a representative draft must satisfy the Continue gate`
    );

    const payload = toSelectionPayload(testCase.draft, offer);
    assertWirePayload(payload, testCase.kind, label);
    assert.deepEqual(payload, testCase.expect, `${label}: wrong wire payload`);
  }

  assert.deepEqual(
    [...covered].sort(),
    [...INTERACTIONS].sort(),
    'all five interaction families must be exercised'
  );
});

test('[picker] an incomplete draft never reaches the wire', () => {
  const exact = toMissionOffer(offerByMission('CARD-V2-H-003'));
  assert.equal(
    isDraftComplete(exact, { kind: 'TARGET_FIGHTER', boutId: 101, corner: 'red' }),
    false,
    'a bound method and round are still missing'
  );

  const selectable = toMissionOffer(offerByMission('CARD-V2-M-013'));
  assert.equal(
    isDraftComplete(selectable, {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'method_one', boutId: 101, corner: 'red' },
        { key: 'method_two', boutId: 102, corner: 'blue' },
      ],
    }),
    false,
    'legs that offer a method choice are not complete without one'
  );
});

test('[picker] the payload drops fields the definition never asked for', () => {
  // A WINNER-only mission that somehow received a method must not forward it:
  // the backend answers 409 "This mission does not bind a method".
  const plain = toMissionOffer(offerByMission('CARD-V2-E-001'));
  const payload = toSelectionPayload(
    { kind: 'TARGET_FIGHTER', boutId: 101, corner: 'red', method: 'KO/TKO', round: 3 },
    plain
  );
  assert.deepEqual(payload, { kind: 'TARGET_FIGHTER', bout_id: 101, corner: 'red' });

  // Same for a combo leg whose method the catalog already fixed.
  const fixed = toMissionOffer(offerByMission('CARD-V2-H-007'));
  const comboPayload = toSelectionPayload(
    {
      kind: 'COMBO_BUILDER',
      legs: [
        { key: 'ko_leg', boutId: 101, corner: 'red', method: 'Submission' },
        { key: 'submission_leg', boutId: 102, corner: 'blue' },
        { key: 'decision_leg', boutId: 103, corner: 'red' },
      ],
    },
    fixed
  );
  assert.equal(comboPayload.legs[0].method, undefined, 'a fixed-method leg echoes nothing back');
});

// ---------------------------------------------------------------------------
// The request the backend actually validates
// ---------------------------------------------------------------------------

test('[http] a VOID card reads as locked in the single lock language', () => {
  const vm = toHomeMissions({ ...PAYLOADS.home.open, card_state: 'VOID' }, CARD, 'AUGUST 2026');
  assert.ok(vm.lockLabel.includes('VOID'));
  assert.ok(vm.lockLabel.includes('LOCKED'));
});

test('[http] every real lock_reason maps to a slot lock the UI can render', async () => {
  const seen = new Set();
  for (const scenario of ['locked', 'results-started', 'settled']) {
    const gateway = createHttpMissionGateway({
      baseUrl: '/api',
      fetchImpl: stubFetch(scenario).impl,
      getToken: () => 'test-token',
    });
    const vm = await gateway.getHome({ eventId: 999, card: CARD });
    assert.ok(vm.lockLabel.includes('LOCKED'), `${scenario}: must read as locked`);
    for (const slot of vm.slots) {
      if (slot.state === 'locked') {
        assert.ok(LOCK_REASONS.has(slot.reason), `${scenario}: unknown reason ${slot.reason}`);
        seen.add(slot.reason);
      }
    }
  }
  // `results-started` used to be unreachable because the DTO did not model it.
  assert.ok(seen.has('results-started'), 'RESULTS_STARTED must reach the UI');
  assert.ok(seen.has('picks-closed'), 'PICKS_CLOSED must reach the UI');
});

test('[http] requests carry the app bearer token and the documented shapes', async () => {
  const stub = stubFetch('open');
  const gateway = createHttpMissionGateway({
    baseUrl: '/api',
    fetchImpl: stub.impl,
    getToken: () => 'test-token',
  });

  await gateway.getHome({ eventId: 999, card: CARD });
  const homeCall = stub.calls.at(-1);
  assert.equal(homeCall.url, '/api/missions/home?event_id=999');
  assert.equal(homeCall.method, 'GET');
  assert.equal(homeCall.headers.Authorization, 'Bearer test-token');

  const wire = offerByMission('CARD-V2-H-003');
  const offer = toMissionOffer(wire);
  await gateway.select({
    eventId: 999,
    slot: 2,
    offer,
    selection: { kind: 'TARGET_FIGHTER', boutId: 101, corner: 'red', method: 'KO/TKO', round: 2 },
  });
  const selectCall = stub.calls.at(-1);
  assert.equal(selectCall.url, '/api/missions/select');
  assert.equal(selectCall.method, 'POST');

  const body = JSON.parse(selectCall.body);
  assert.equal(body.event_id, 999);
  assert.equal(body.slot, 2, 'the wire is one-based; there is no slot_index');
  assert.equal(body.slot_index, undefined);
  assert.equal(body.offer_id, wire.offer_id, 'select addresses the offer');
  assert.equal(body.mission_id, undefined, 'the mission id is not the address');
  assert.deepEqual(body.selection, {
    kind: 'TARGET_FIGHTER',
    bout_id: 101,
    corner: 'red',
    method: 'KO_TKO',
    round: 2,
  });

  await gateway.acknowledgeCelebration('cel-1');
  const ackCall = stub.calls.at(-1);
  assert.equal(ackCall.url, '/api/missions/celebrations/cel-1/ack');
  assert.equal(ackCall.method, 'POST');
});

test('[http] the request satisfies every field the backend reported missing', async () => {
  // The generator captured a REAL pydantic 422 for the body the broken frontend
  // used to send. The fields it called "missing" are exactly the fields the
  // current body must contain — the backend defines the list, not this test.
  const missing = PAYLOADS.errors.legacy_frontend_body_422.detail
    .filter((entry) => entry.type === 'missing')
    .map((entry) => entry.loc[entry.loc.length - 1]);
  assert.ok(missing.length > 0, 'the captured 422 must actually list missing fields');

  const stub = stubFetch('open');
  const gateway = createHttpMissionGateway({
    baseUrl: '/api',
    fetchImpl: stub.impl,
    getToken: () => 'test-token',
  });
  await gateway.select({
    eventId: 999,
    slot: 1,
    offer: toMissionOffer(offerByMission('CARD-V2-E-004')),
    selection: { kind: 'AUTO' },
  });

  const body = JSON.parse(stub.calls.at(-1).body);
  for (const field of missing) {
    assert.ok(field in body, `the body is still missing "${field}" — this is the original 422`);
  }
  assert.match(
    body.idempotency_key,
    /^[A-Za-z0-9._:-]{8,128}$/,
    'the key must satisfy SelectMissionCommand'
  );
});

test('[http] retrying the same selection reuses one idempotency key', async () => {
  const stub = stubFetch('open');
  const gateway = createHttpMissionGateway({
    baseUrl: '/api',
    fetchImpl: stub.impl,
    getToken: () => 'test-token',
  });
  const offer = toMissionOffer(offerByMission('CARD-V2-E-001'));
  const request = {
    eventId: 999,
    slot: 1,
    offer,
    selection: { kind: 'TARGET_FIGHTER', boutId: 101, corner: 'red' },
  };

  await gateway.select(request);
  await gateway.select(request);

  const bodies = stub.calls
    .filter((call) => call.url.includes('/missions/select'))
    .map((call) => JSON.parse(call.body));
  assert.equal(bodies.length, 2);
  assert.equal(
    bodies[0].idempotency_key,
    bodies[1].idempotency_key,
    'a retry must replay the receipt instead of creating a second assignment'
  );

  // A DIFFERENT selection must not collide onto that key: the backend answers
  // IDEMPOTENCY_CONFLICT when one key is reused with another request.
  const otherCorner = idempotencyKeyFor({
    eventId: 999,
    slot: 1,
    offerId: offer.offerId,
    selection: { kind: 'TARGET_FIGHTER', bout_id: 101, corner: 'blue' },
  });
  assert.notEqual(bodies[0].idempotency_key, otherCorner);

  // A caller may still supply its own.
  await gateway.select({ ...request, idempotencyKey: 'caller-supplied-key' });
  assert.equal(JSON.parse(stub.calls.at(-1).body).idempotency_key, 'caller-supplied-key');
});

// ---------------------------------------------------------------------------
// Errors: FastAPI wraps everything in `detail`
// ---------------------------------------------------------------------------

test('[http] mission error codes survive the detail envelope', async () => {
  const cases = [
    ['slot_locked_409', 409, 'SLOT_LOCKED'],
    ['offer_not_found_409', 409, 'OFFER_NOT_FOUND'],
    ['already_selected_409', 409, 'ALREADY_SELECTED'],
    ['idempotency_conflict_409', 409, 'IDEMPOTENCY_CONFLICT'],
    ['invalid_selection_409', 409, 'INVALID_SELECTION'],
    ['card_not_found_404', 404, 'NOT_AVAILABLE'],
  ];

  for (const [fixtureKey, status, expected] of cases) {
    const body = PAYLOADS.errors[fixtureKey];
    const gateway = createHttpMissionGateway({
      baseUrl: '/api',
      fetchImpl: async () => json(body, status),
      getToken: () => 'test-token',
    });

    await assert.rejects(
      () =>
        gateway.select({
          eventId: 999,
          slot: 1,
          offer: THROWAWAY_OFFER,
          selection: { kind: 'AUTO' },
        }),
      (error) => {
        assert.ok(error instanceof MissionGatewayError, `${fixtureKey}: wrong error type`);
        assert.equal(error.code, expected, `${fixtureKey}: reading detail.code failed`);
        assert.equal(error.message, body.detail.message, `${fixtureKey}: message lost`);
        return true;
      }
    );
  }
});

test('[http] a 401 is reported as UNAUTHENTICATED, not as a crash', async () => {
  const gateway = createHttpMissionGateway({
    baseUrl: '/api',
    fetchImpl: async () => json(PAYLOADS.errors.unauthenticated_401, 401),
    getToken: () => null,
  });

  await assert.rejects(
    () => gateway.getHome({ eventId: 999, card: CARD }),
    (error) => {
      assert.ok(error instanceof MissionGatewayError);
      assert.equal(error.code, 'UNAUTHENTICATED');
      return true;
    }
  );
});

test('[http] a 422 validation array degrades to a readable message', async () => {
  const gateway = createHttpMissionGateway({
    baseUrl: '/api',
    fetchImpl: async () => json(PAYLOADS.errors.legacy_frontend_body_422, 422),
    getToken: () => 'test-token',
  });

  await assert.rejects(
    () =>
      gateway.select({
        eventId: 999,
        slot: 1,
        offer: THROWAWAY_OFFER,
        selection: { kind: 'AUTO' },
      }),
    (error) => {
      assert.equal(error.code, 'UNKNOWN');
      assert.ok(error.message.length > 0, 'a validation error must still say something');
      assert.ok(!error.message.includes('[object Object]'), 'the array must not be stringified raw');
      return true;
    }
  );
});

test('[http] a transport failure is reported as NETWORK', async () => {
  const gateway = createHttpMissionGateway({
    baseUrl: '/api',
    fetchImpl: async () => {
      throw new TypeError('Failed to fetch');
    },
    getToken: () => 'test-token',
  });

  await assert.rejects(
    () => gateway.getHome({ eventId: 999, card: CARD }),
    (error) => {
      assert.equal(error.code, 'NETWORK');
      return true;
    }
  );
});

// ---------------------------------------------------------------------------
// Slice 3 — streak, level and celebrations over the real profile payload
// ---------------------------------------------------------------------------

const PROFILE_CONTEXT = { userName: 'Jose', memberSince: 'JAN 2026' };

test('[profile] the streak milestone label comes from the backend, not from React', () => {
  const hub = toProfileHub(PAYLOADS.profile, {
    ...PROFILE_CONTEXT,
    monthly: { monthLabel: 'AUGUST' },
  });

  assert.equal(hub.streak.current, PAYLOADS.profile.current_streak);
  assert.equal(hub.streak.best, PAYLOADS.profile.best_streak);
  assert.equal(hub.streak.nextMilestoneLabel, PAYLOADS.profile.next_streak_milestone_label);
  assert.notEqual(
    hub.streak.nextMilestoneLabel,
    '',
    'the label must be carried through, not left blank'
  );
  assert.equal(hub.streak.justBroken, false);
});

test('[profile] celebrations map from typed metadata, not from the display copy', () => {
  const hub = toProfileHub(PAYLOADS.profile, {
    ...PROFILE_CONTEXT,
    monthly: { monthLabel: 'AUGUST' },
  });

  assert.equal(
    hub.pendingCelebrations.length,
    PAYLOADS.profile.celebrations.length,
    'every celebration the backend sent must reach the surface'
  );

  const streak = hub.pendingCelebrations.find((c) => c.kind === 'streak-milestone');
  assert.ok(streak, 'a STREAK_MILESTONE must map to the streak-milestone variant');
  assert.equal(streak.count, 3);
  assert.equal(streak.bonusXp, 2);
  assert.equal(typeof streak.id, 'string');

  const mission = hub.pendingCelebrations.find((c) => c.kind === 'mission-completed');
  assert.ok(mission);
  assert.equal(mission.name, 'PERFECT MAIN CARD');
  assert.equal(mission.xp, 3);
});

test('[profile] a celebration with an incomplete payload is dropped, not faked', () => {
  const hub = toProfileHub(
    {
      ...PAYLOADS.profile,
      celebrations: [
        {
          id: 'c_bad',
          kind: 'STREAK_MILESTONE',
          presentation: 'FULL_SCREEN',
          heading: '5 card streak',
          message: 'Streak milestone reached',
          metadata: { streak: 5 }, // no bonus_xp
        },
      ],
    },
    { ...PROFILE_CONTEXT, monthly: { monthLabel: 'AUGUST' } }
  );

  assert.equal(
    hub.pendingCelebrations.length,
    0,
    'a congratulation with the wrong number is worse than none'
  );
});

test('[profile] history rows carry the card name the backend resolved', () => {
  const hub = toProfileHub(PAYLOADS.profile, {
    ...PROFILE_CONTEXT,
    monthly: { monthLabel: 'AUGUST' },
  });

  const settled = PAYLOADS.profile.history[0];
  assert.ok(settled, 'the fixture must contain a settled assignment');
  assert.equal(hub.history[0].eventLabel, settled.event_label ?? '');
});

test('[profile] the backend answers the streak history the hub needs', () => {
  const rows = PAYLOADS.profile.streak_history ?? [];
  assert.ok(rows.length > 0, 'the profile payload must carry settled streak cards');

  for (const row of rows) {
    assert.ok(['ADVANCED', 'BROKEN', 'UNCHANGED'].includes(row.outcome));
    assert.ok(row.coverage_percent >= 0 && row.coverage_percent <= 100);
    assert.ok(
      row.picked <= row.denominator,
      'coverage can never exceed the frozen denominator'
    );
  }
});

// ---------------------------------------------------------------------------
// Slice 4 — the Admin gateway
// ---------------------------------------------------------------------------

function adminStub() {
  const calls = [];
  const control = { state: 'OPEN' };
  const impl = async (url, init = {}) => {
    const path = String(url);
    const method = init.method ?? 'GET';
    calls.push({ path, method, body: init.body });

    if (path.includes('/admin/missions/cards/')) {
      const action = path.split('/').pop();
      if (method === 'POST') {
        control.state =
          action === 'close' ? 'CLOSED' : action === 'void' ? 'VOID' : 'OPEN';
      }
      return json({
        event_id: 999,
        state: control.state,
        reason: 'because',
        actor_id: 'admin-1',
        updated_at: '2026-08-02T00:00:00Z',
        voided_assignments: control.state === 'VOID' ? 2 : 0,
        revision: 3,
      });
    }
    if (path.includes('/reconciliation/preview')) {
      return json({
        preview_version: '1',
        plan_id: 'plan_abc',
        current_digest: 'a',
        desired_digest: 'b',
        converged: false,
        safe_to_apply: true,
        operations: [
          {
            operation_id: 'op1',
            action: 'UPDATE',
            entity_type: 'USER_PROGRESSION',
            entity_id: 'user-1',
            impact: 'PROGRESSION_REBUILD',
            changed_fields: ['lifetime_xp', 'level'],
            before: { lifetime_xp: 0, level: 1 },
            after: { lifetime_xp: 6, level: 2 },
          },
        ],
        unchanged_entities: ['user-2'],
        blockers: [],
      });
    }
    if (path.includes('/reconciliation/apply')) {
      return json({ plan_id: 'plan_abc', applied: 1, skipped: 0, converged: true });
    }
    return json(PAYLOADS.errors.card_not_found_404, 404);
  };
  return { impl, calls };
}

function adminGateway() {
  const stub = adminStub();
  return {
    stub,
    gateway: createHttpMissionGateway({
      baseUrl: '/api',
      fetchImpl: stub.impl,
      getToken: () => 'admin-token',
    }),
  };
}

test('[admin] a card action posts the reason and returns the new state', async () => {
  const { gateway, stub } = adminGateway();

  const result = await gateway.admin.actOnCard({
    eventId: 999,
    action: 'void',
    reason: 'Event cancelled',
  });

  assert.equal(result.state, 'VOID');
  assert.equal(result.voidedAssignments, 2);
  assert.equal(result.actorId, 'admin-1');

  const call = stub.calls.at(-1);
  assert.equal(call.method, 'POST');
  assert.ok(call.path.endsWith('/admin/missions/cards/999/void'));
  assert.deepEqual(JSON.parse(call.body), { reason: 'Event cancelled' });
});

test('[admin] the reconciliation preview renders before/after as finished text', async () => {
  const { gateway } = adminGateway();

  const preview = await gateway.admin.previewReconciliation({ eventId: 999 });

  assert.equal(preview.planId, 'plan_abc');
  assert.equal(preview.converged, false);
  assert.equal(preview.safeToApply, true);
  assert.equal(preview.unchangedCount, 1);

  const [op] = preview.operations;
  assert.equal(op.beforeText, 'lifetime_xp=0, level=1');
  assert.equal(op.afterText, 'lifetime_xp=6, level=2');
});

test('[admin] an empty reconciliation scope is never sent as a bare query', async () => {
  const { gateway, stub } = adminGateway();

  await gateway.admin.previewReconciliation({ userId: 'user-1' });

  const call = stub.calls.at(-1);
  assert.ok(call.path.includes('user_id=user-1'));
  assert.ok(!call.path.includes('event_id='), 'unset scope keys must not be sent');
});

test('[admin] apply echoes the reviewed plan id back to the server', async () => {
  const { gateway, stub } = adminGateway();

  const result = await gateway.admin.applyReconciliation({
    planId: 'plan_abc',
    reason: 'Repairing drift',
    userId: 'user-1',
  });

  assert.equal(result.applied, 1);
  assert.equal(result.converged, true);
  assert.equal(JSON.parse(stub.calls.at(-1).body).plan_id, 'plan_abc');
});

test('[admin] the mock gateway exposes no admin authority', async () => {
  const gateway = createMockGateway({ scenarioId: 'home-open' });

  assert.equal(
    gateway.admin,
    undefined,
    'the Lab adapter must not appear to hold Admin rights'
  );
});
